In [13]:
import numpy as np;

data = np.random.randn(2, 3);
print(data, '\n');
print(data + data, '\n');
print(data + 10, '\n');
print(data.shape, '\n');
print(data.dtype, '\n');
print(data.ndim, '\n');

[[-0.41888932  1.06206403  0.3412631 ]
 [ 0.2069835  -0.94539875  1.24575561]] 

[[-0.83777864  2.12412806  0.68252619]
 [ 0.413967   -1.89079751  2.49151122]] 

[[ 9.58111068 11.06206403 10.3412631 ]
 [10.2069835   9.05460125 11.24575561]] 

(2, 3) 

float64 

2 



In [19]:
print(np.zeros(10), '\n');
print(np.zeros((3, 6)), '\n');
print(np.zeros((2, 3, 4)), '\n');

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] 



In [23]:
print(np.empty((3, 6)), '\n');

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 



In [25]:
arr = np.array([1,2,3,4]);
print(arr.astype(np.float64));

[1. 2. 3. 4.]


In [38]:
arr = np.array([2, 4, 8], dtype='int64');
print(arr, '\n');
print(arr * 2, '\n');
print(arr * arr, '\n');
print((arr / 2).astype(np.int64), '\n');
print(arr ** 3, '\n');
print(np.sqrt(arr), '\n');
print(np.exp(arr), '\n');
print(np.mean(arr), '\n');
print(np.sum(arr), '\n');
print(np.cumsum(arr), '\n');
print(np.sort(arr), '\n');

[2 4 8] 

[ 4  8 16] 

[ 4 16 64] 

[1 2 4] 

[  8  64 512] 

[1.41421356 2.         2.82842712] 

[   7.3890561    54.59815003 2980.95798704] 

4.666666666666667 

14 

[ 2  6 14] 

[2 4 8] 



In [40]:
arr = np.array([1, 2, 4, 8]);
arr2 = np.array([5, 6, 8, 1]);
print(arr > arr2);

[False False False  True]


In [46]:
arr = np.arange(10);
print(arr);

arr2 = arr[5:8];
print(arr2);

arr[:3]=0;
print(arr);

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[0 0 0 3 4 5 6 7 8 9]


In [58]:
nameArr = np.array(['Irfan', 'Usman', 'Ali', 'Abdullah']);
numArr = np.random.randn(4, 3);

print(nameArr, '\n');
print(numArr, '\n');

print(nameArr == 'Irfan', '\n');
print(numArr[nameArr == 'Irfan'], '\n');
print(numArr[~(nameArr == 'Irfan')], '\n');

print(np.unique(nameArr));

['Irfan' 'Usman' 'Ali' 'Abdullah'] 

[[ 1.50846449 -0.19703401  0.06197425]
 [-0.45535631  1.51420397 -0.74754373]
 [ 0.23427486 -0.87134203 -0.01279989]
 [ 0.40263386  0.30876175  0.61154819]] 

[ True False False False] 

[[ 1.50846449 -0.19703401  0.06197425]] 

[[-0.45535631  1.51420397 -0.74754373]
 [ 0.23427486 -0.87134203 -0.01279989]
 [ 0.40263386  0.30876175  0.61154819]] 

['Abdullah' 'Ali' 'Irfan' 'Usman']


In [59]:
numArr1 = np.random.randn(4);
print(numArr1, '\n');

numArr2 = np.random.randn(4);
print(numArr2, '\n');

print(np.maximum(numArr1, numArr2), '\n');
print(np.minimum(numArr1, numArr2), '\n');

[-0.30590616  0.12910442  0.97538446  0.52154849] 

[-1.15068533 -2.00276097  1.57355321  1.42891902] 

[-0.30590616  0.12910442  1.57355321  1.42891902] 

[-1.15068533 -2.00276097  0.97538446  0.52154849] 

